//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.1008
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.App_GlobalResources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Abdomen.
        /// </summary>
        public static string abdomen {
            get {
                return ResourceManager.GetString("abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar.
        /// </summary>
        public static string adicionar {
            get {
                return ResourceManager.GetString("adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Altura.
        /// </summary>
        public static string altura {
            get {
                return ResourceManager.GetString("altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aluno.
        /// </summary>
        public static string aluno {
            get {
                return ResourceManager.GetString("aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Direito.
        /// </summary>
        public static string ante_braco_direito {
            get {
                return ResourceManager.GetString("ante_braco_direito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Antebraço Esquerdo.
        /// </summary>
        public static string ante_braco_esquerdo {
            get {
                return ResourceManager.GetString("ante_braco_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apelido.
        /// </summary>
        public static string apelido {
            get {
                return ResourceManager.GetString("apelido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Apelido/Fantasia.
        /// </summary>
        public static string apelido_fantasia {
            get {
                return ResourceManager.GetString("apelido_fantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atendente.
        /// </summary>
        public static string atendente {
            get {
                return ResourceManager.GetString("atendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo Desde.
        /// </summary>
        public static string ativo_desde {
            get {
                return ResourceManager.GetString("ativo_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bairro.
        /// </summary>
        public static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Direito.
        /// </summary>
        public static string biceps_direito {
            get {
                return ResourceManager.GetString("biceps_direito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bíceps Esquerdo.
        /// </summary>
        public static string biceps_esquerdo {
            get {
                return ResourceManager.GetString("biceps_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrado Desde.
        /// </summary>
        public static string cadastrado_desde {
            get {
                return ResourceManager.GetString("cadastrado_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cep.
        /// </summary>
        public static string cep {
            get {
                return ResourceManager.GetString("cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cidade.
        /// </summary>
        public static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cintura.
        /// </summary>
        public static string cintura {
            get {
                return ResourceManager.GetString("cintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cód. Atividade.
        /// </summary>
        public static string cod_atividade {
            get {
                return ResourceManager.GetString("cod_atividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cód. Modalidade.
        /// </summary>
        public static string cod_modalidade {
            get {
                return ResourceManager.GetString("cod_modalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de Barra.
        /// </summary>
        public static string codigo_barra {
            get {
                return ResourceManager.GetString("codigo_barra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código do Funconário.
        /// </summary>
        public static string codigo_funcionario {
            get {
                return ResourceManager.GetString("codigo_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código da Medida.
        /// </summary>
        public static string codigo_medida {
            get {
                return ResourceManager.GetString("codigo_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código da Pessoa.
        /// </summary>
        public static string codigo_pessoa {
            get {
                return ResourceManager.GetString("codigo_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Complemento.
        /// </summary>
        public static string complemento {
            get {
                return ResourceManager.GetString("complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Costa.
        /// </summary>
        public static string costa {
            get {
                return ResourceManager.GetString("costa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Direita.
        /// </summary>
        public static string coxa_direita {
            get {
                return ResourceManager.GetString("coxa_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Coxa Esquerda.
        /// </summary>
        public static string coxa_esquerda {
            get {
                return ResourceManager.GetString("coxa_esquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cpf/Cnpj.
        /// </summary>
        public static string cpf_cnpj {
            get {
                return ResourceManager.GetString("cpf_cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir Nova.
        /// </summary>
        public static string criar_nova {
            get {
                return ResourceManager.GetString("criar_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inserir Novo.
        /// </summary>
        public static string criar_novo {
            get {
                return ResourceManager.GetString("criar_novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Matrícula.
        /// </summary>
        public static string data_matricula {
            get {
                return ResourceManager.GetString("data_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data da Medida.
        /// </summary>
        public static string data_medida {
            get {
                return ResourceManager.GetString("data_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Nascimento.
        /// </summary>
        public static string data_nascimento {
            get {
                return ResourceManager.GetString("data_nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Trancamento.
        /// </summary>
        public static string data_trancamento {
            get {
                return ResourceManager.GetString("data_trancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você Realmente deseja apagar esse registro?.
        /// </summary>
        public static string deseja_apagar {
            get {
                return ResourceManager.GetString("deseja_apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Detalhes.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dia Venciamento.
        /// </summary>
        public static string dia_vencimento {
            get {
                return ResourceManager.GetString("dia_vencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Nome é requerido..
        /// </summary>
        public static string erro_nome {
            get {
                return ResourceManager.GetString("erro_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O campo Valor é requerido..
        /// </summary>
        public static string erro_valor {
            get {
                return ResourceManager.GetString("erro_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feminino.
        /// </summary>
        public static string feminino {
            get {
                return ResourceManager.GetString("feminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fornecedor.
        /// </summary>
        public static string fornecedor {
            get {
                return ResourceManager.GetString("fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Funcionário.
        /// </summary>
        public static string funcionario {
            get {
                return ResourceManager.GetString("funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Aluno.
        /// </summary>
        public static string gerenciar_aluno {
            get {
                return ResourceManager.GetString("gerenciar_aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Atividades.
        /// </summary>
        public static string gerenciar_atividades {
            get {
                return ResourceManager.GetString("gerenciar_atividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Funcionário.
        /// </summary>
        public static string gerenciar_funcionario {
            get {
                return ResourceManager.GetString("gerenciar_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Medida.
        /// </summary>
        public static string gerenciar_medida {
            get {
                return ResourceManager.GetString("gerenciar_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Modalidade.
        /// </summary>
        public static string gerenciar_modalidade {
            get {
                return ResourceManager.GetString("gerenciar_modalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gerenciar Produto.
        /// </summary>
        public static string gerenciar_produto {
            get {
                return ResourceManager.GetString("gerenciar_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gordura.
        /// </summary>
        public static string gordura {
            get {
                return ResourceManager.GetString("gordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IMC.
        /// </summary>
        public static string imc {
            get {
                return ResourceManager.GetString("imc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Instrutor.
        /// </summary>
        public static string instrutor {
            get {
                return ResourceManager.GetString("instrutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Masculino.
        /// </summary>
        public static string masculino {
            get {
                return ResourceManager.GetString("masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Matrícula.
        /// </summary>
        public static string matricula {
            get {
                return ResourceManager.GetString("matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Medida.
        /// </summary>
        public static string medida {
            get {
                return ResourceManager.GetString("medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modalidade.
        /// </summary>
        public static string modalidade {
            get {
                return ResourceManager.GetString("modalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Atividade.
        /// </summary>
        public static string nome_atividade {
            get {
                return ResourceManager.GetString("nome_atividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome/Razão Social.
        /// </summary>
        public static string nome_razao {
            get {
                return ResourceManager.GetString("nome_razao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Novo.
        /// </summary>
        public static string novo {
            get {
                return ResourceManager.GetString("novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ombro.
        /// </summary>
        public static string ombro {
            get {
                return ResourceManager.GetString("ombro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Direita.
        /// </summary>
        public static string panturrilha_direita {
            get {
                return ResourceManager.GetString("panturrilha_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Panturrilha Esquerdo.
        /// </summary>
        public static string panturrilha_esquerdo {
            get {
                return ResourceManager.GetString("panturrilha_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peitoral.
        /// </summary>
        public static string peitoral {
            get {
                return ResourceManager.GetString("peitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Permição do Funcionário.
        /// </summary>
        public static string permicao {
            get {
                return ResourceManager.GetString("permicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Peso.
        /// </summary>
        public static string peso {
            get {
                return ResourceManager.GetString("peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preço de Custo.
        /// </summary>
        public static string preco_custo {
            get {
                return ResourceManager.GetString("preco_custo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preço de Venda.
        /// </summary>
        public static string preco_venda {
            get {
                return ResourceManager.GetString("preco_venda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Produto.
        /// </summary>
        public static string produto {
            get {
                return ResourceManager.GetString("produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Proprietário.
        /// </summary>
        public static string proprietario {
            get {
                return ResourceManager.GetString("proprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quadril.
        /// </summary>
        public static string quadril {
            get {
                return ResourceManager.GetString("quadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade.
        /// </summary>
        public static string quantidade {
            get {
                return ResourceManager.GetString("quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade Mínima.
        /// </summary>
        public static string quantidade_minima {
            get {
                return ResourceManager.GetString("quantidade_minima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rg.
        /// </summary>
        public static string rg {
            get {
                return ResourceManager.GetString("rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rua.
        /// </summary>
        public static string rua {
            get {
                return ResourceManager.GetString("rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Salvar.
        /// </summary>
        public static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione.
        /// </summary>
        public static string selecione {
            get {
                return ResourceManager.GetString("selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sexo.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone 1.
        /// </summary>
        public static string telefone1 {
            get {
                return ResourceManager.GetString("telefone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone 2.
        /// </summary>
        public static string telefone2 {
            get {
                return ResourceManager.GetString("telefone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Valor Mensalidade.
        /// </summary>
        public static string valor_mensalidade {
            get {
                return ResourceManager.GetString("valor_mensalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar Para Lista.
        /// </summary>
        public static string voltar_para_lista {
            get {
                return ResourceManager.GetString("voltar_para_lista", resourceCulture);
            }
        }
    }
}
