//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.App_GlobalResources.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        public static string abdomen {
            get {
                return ResourceManager.GetString("abdomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string adicionar {
            get {
                return ResourceManager.GetString("adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        public static string altura {
            get {
                return ResourceManager.GetString("altura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno.
        /// </summary>
        public static string aluno {
            get {
                return ResourceManager.GetString("aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antebraço Direito.
        /// </summary>
        public static string ante_braco_direito {
            get {
                return ResourceManager.GetString("ante_braco_direito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antebraço Esquerdo.
        /// </summary>
        public static string ante_braco_esquerdo {
            get {
                return ResourceManager.GetString("ante_braco_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string apelido {
            get {
                return ResourceManager.GetString("apelido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido/Fantasia.
        /// </summary>
        public static string apelido_fantasia {
            get {
                return ResourceManager.GetString("apelido_fantasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendente.
        /// </summary>
        public static string atendente {
            get {
                return ResourceManager.GetString("atendente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ativo Desde.
        /// </summary>
        public static string ativo_desde {
            get {
                return ResourceManager.GetString("ativo_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string bairro {
            get {
                return ResourceManager.GetString("bairro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bíceps Direito.
        /// </summary>
        public static string biceps_direito {
            get {
                return ResourceManager.GetString("biceps_direito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bíceps Esquerdo.
        /// </summary>
        public static string biceps_esquerdo {
            get {
                return ResourceManager.GetString("biceps_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrado Desde.
        /// </summary>
        public static string cadastrado_desde {
            get {
                return ResourceManager.GetString("cadastrado_desde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string cancelar {
            get {
                return ResourceManager.GetString("cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep.
        /// </summary>
        public static string cep {
            get {
                return ResourceManager.GetString("cep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string cidade {
            get {
                return ResourceManager.GetString("cidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cintura.
        /// </summary>
        public static string cintura {
            get {
                return ResourceManager.GetString("cintura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        public static string codigo {
            get {
                return ResourceManager.GetString("codigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código de Barra.
        /// </summary>
        public static string codigo_barra {
            get {
                return ResourceManager.GetString("codigo_barra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código do Funconário.
        /// </summary>
        public static string codigo_funcionario {
            get {
                return ResourceManager.GetString("codigo_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Medida.
        /// </summary>
        public static string codigo_medida {
            get {
                return ResourceManager.GetString("codigo_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código da Pessoa.
        /// </summary>
        public static string codigo_pessoa {
            get {
                return ResourceManager.GetString("codigo_pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento.
        /// </summary>
        public static string complemento {
            get {
                return ResourceManager.GetString("complemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa.
        /// </summary>
        public static string costa {
            get {
                return ResourceManager.GetString("costa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxa Direita.
        /// </summary>
        public static string coxa_direita {
            get {
                return ResourceManager.GetString("coxa_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxa Esquerda.
        /// </summary>
        public static string coxa_esquerda {
            get {
                return ResourceManager.GetString("coxa_esquerda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf/Cnpj.
        /// </summary>
        public static string cpf_cnpj {
            get {
                return ResourceManager.GetString("cpf_cnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir Nova.
        /// </summary>
        public static string criar_nova {
            get {
                return ResourceManager.GetString("criar_nova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserir Novo.
        /// </summary>
        public static string criar_novo {
            get {
                return ResourceManager.GetString("criar_novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Matrícula.
        /// </summary>
        public static string data_matricula {
            get {
                return ResourceManager.GetString("data_matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data da Medida.
        /// </summary>
        public static string data_medida {
            get {
                return ResourceManager.GetString("data_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Nascimento.
        /// </summary>
        public static string data_nascimento {
            get {
                return ResourceManager.GetString("data_nascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Trancamento.
        /// </summary>
        public static string data_trancamento {
            get {
                return ResourceManager.GetString("data_trancamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você Realmente deseja apagar esse registro?.
        /// </summary>
        public static string deseja_apagar {
            get {
                return ResourceManager.GetString("deseja_apagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string detalhes {
            get {
                return ResourceManager.GetString("detalhes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia Venciamento.
        /// </summary>
        public static string dia_vencimento {
            get {
                return ResourceManager.GetString("dia_vencimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar.
        /// </summary>
        public static string editar {
            get {
                return ResourceManager.GetString("editar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Nome é requerido..
        /// </summary>
        public static string erro_nome {
            get {
                return ResourceManager.GetString("erro_nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo Valor é requerido..
        /// </summary>
        public static string erro_valor {
            get {
                return ResourceManager.GetString("erro_valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string estado {
            get {
                return ResourceManager.GetString("estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir.
        /// </summary>
        public static string excluir {
            get {
                return ResourceManager.GetString("excluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string feminino {
            get {
                return ResourceManager.GetString("feminino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fornecedor.
        /// </summary>
        public static string fornecedor {
            get {
                return ResourceManager.GetString("fornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funcionário.
        /// </summary>
        public static string funcionario {
            get {
                return ResourceManager.GetString("funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Aluno.
        /// </summary>
        public static string gerenciar_aluno {
            get {
                return ResourceManager.GetString("gerenciar_aluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Funcionário.
        /// </summary>
        public static string gerenciar_funcionario {
            get {
                return ResourceManager.GetString("gerenciar_funcionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Medida.
        /// </summary>
        public static string gerenciar_medida {
            get {
                return ResourceManager.GetString("gerenciar_medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Modalidade.
        /// </summary>
        public static string gerenciar_modalidade {
            get {
                return ResourceManager.GetString("gerenciar_modalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerenciar Produto.
        /// </summary>
        public static string gerenciar_produto {
            get {
                return ResourceManager.GetString("gerenciar_produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gordura.
        /// </summary>
        public static string gordura {
            get {
                return ResourceManager.GetString("gordura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMC.
        /// </summary>
        public static string imc {
            get {
                return ResourceManager.GetString("imc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrutor.
        /// </summary>
        public static string instrutor {
            get {
                return ResourceManager.GetString("instrutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string masculino {
            get {
                return ResourceManager.GetString("masculino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        public static string matricula {
            get {
                return ResourceManager.GetString("matricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medida.
        /// </summary>
        public static string medida {
            get {
                return ResourceManager.GetString("medida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalidade.
        /// </summary>
        public static string modalidade {
            get {
                return ResourceManager.GetString("modalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string nome {
            get {
                return ResourceManager.GetString("nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome/Razão Social.
        /// </summary>
        public static string nome_razao {
            get {
                return ResourceManager.GetString("nome_razao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string novo {
            get {
                return ResourceManager.GetString("novo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string numero {
            get {
                return ResourceManager.GetString("numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ombro.
        /// </summary>
        public static string ombro {
            get {
                return ResourceManager.GetString("ombro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panturrilha Direita.
        /// </summary>
        public static string panturrilha_direita {
            get {
                return ResourceManager.GetString("panturrilha_direita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panturrilha Esquerdo.
        /// </summary>
        public static string panturrilha_esquerdo {
            get {
                return ResourceManager.GetString("panturrilha_esquerdo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peitoral.
        /// </summary>
        public static string peitoral {
            get {
                return ResourceManager.GetString("peitoral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permição do Funcionário.
        /// </summary>
        public static string permicao {
            get {
                return ResourceManager.GetString("permicao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso.
        /// </summary>
        public static string peso {
            get {
                return ResourceManager.GetString("peso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de Custo.
        /// </summary>
        public static string preco_custo {
            get {
                return ResourceManager.GetString("preco_custo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preço de Venda.
        /// </summary>
        public static string preco_venda {
            get {
                return ResourceManager.GetString("preco_venda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto.
        /// </summary>
        public static string produto {
            get {
                return ResourceManager.GetString("produto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proprietário.
        /// </summary>
        public static string proprietario {
            get {
                return ResourceManager.GetString("proprietario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadril.
        /// </summary>
        public static string quadril {
            get {
                return ResourceManager.GetString("quadril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade.
        /// </summary>
        public static string quantidade {
            get {
                return ResourceManager.GetString("quantidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Mínima.
        /// </summary>
        public static string quantidade_minima {
            get {
                return ResourceManager.GetString("quantidade_minima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rg.
        /// </summary>
        public static string rg {
            get {
                return ResourceManager.GetString("rg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rua.
        /// </summary>
        public static string rua {
            get {
                return ResourceManager.GetString("rua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string salvar {
            get {
                return ResourceManager.GetString("salvar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione.
        /// </summary>
        public static string selecione {
            get {
                return ResourceManager.GetString("selecione", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string senha {
            get {
                return ResourceManager.GetString("senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexo.
        /// </summary>
        public static string sexo {
            get {
                return ResourceManager.GetString("sexo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 1.
        /// </summary>
        public static string telefone1 {
            get {
                return ResourceManager.GetString("telefone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone 2.
        /// </summary>
        public static string telefone2 {
            get {
                return ResourceManager.GetString("telefone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string valor {
            get {
                return ResourceManager.GetString("valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Mensalidade.
        /// </summary>
        public static string valor_mensalidade {
            get {
                return ResourceManager.GetString("valor_mensalidade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar Para Lista.
        /// </summary>
        public static string voltar_para_lista {
            get {
                return ResourceManager.GetString("voltar_para_lista", resourceCulture);
            }
        }
    }
}
